name: base_flutter
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #toast
  fluttertoast: ^3.1.3
  #本地存储
  shared_preferences: ^0.4.0
  #屏幕适配
  flutter_screenutil: ^0.5.3
  # dio网络请求框架
  dio: ^3.0.9
  # dio cookie管理
  dio_cookie_manager: ^1.0.0
  # 本地路径管理
  path_provider: ^1.6.5
#  # aes加密库
#  cipher2: ^0.3.5
  #状态管理
  provider: ^4.0.1
  #权限获取
  permission_handler: ^5.0.1+1
  #刷新框架
  pull_to_refresh: ^1.6.0
  #消息总线 eventBus
  event_bus: ^1.1.1
  #生命周期
  flutter_lifecycle_state: ^1.0.0
  #时选择器
  flutter_datetime_picker: ^1.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/

