name: base_flutter
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #toast
  flutter_styled_toast: ^2.0.0
  #本地存储
  shared_preferences: ^2.0.3
  #屏幕适配
  flutter_screenutil: ^5.0.0-nullsafety.11
  # dio网络请求框架
  dio: ^4.0.0-beta5
  # dio cookie管理
  dio_cookie_manager: ^2.0.0-beta1

  cached_network_image: ^3.0.0-nullsafety

  # 本地路径管理
  path_provider: ^2.0.1
#  # aes加密库
#  cipher2: ^0.3.5
  #状态管理
  provider: ^4.0.1
  #刷新框架
  pull_to_refresh: ^1.6.4
  #消息总线 eventBus
  event_bus: ^1.1.1
  #生命周期
  flutter_lifecycle_state: ^1.0.0
  #时选择器
  flutter_datetime_picker: ^1.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/

