name: base_flutter
description: A new Flutter project.
version: 0.0.1
author: kzCai
homepage: https://github.com/c786909486/base_flutter_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #toast
  ftoast: ^2.0.0
  #本地存储
  shared_preferences: ^2.1.0
  sp_util: ^2.0.3
  # dio网络请求框架
  dio_net_work:
    git:
      url: https://gitee.com/code1993/dio_net_work_package.git


  cached_network_image: ^3.2.3


#  # aes加密库
#  cipher2: ^0.3.5
  #状态管理
  provider: ^6.0.5
  #权限获取
#  permission_handler: 8.1.0
  #刷新框架
#  pull_to_refresh:
#    git: https://gitee.com/code1993/pull_to_refresh.git
  pull_to_refresh: ^2.0.0
  #消息总线 eventBus
  event_bus: ^2.0.0
  #生命周期
#  flutter_lifecycle:
#    git:
#      url: 'https://github.com/c786909486/flutter_lifecycle.git'
  #时选择器
  flutter_datetime_picker: ^1.5.1

  ionicons: ^0.2.2

  photo_view: ^0.14.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/

